---
name: Seek the Joy
description: Mundana is a free Jekyll theme for awesome people like you, Medium like.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: eric.laurits@gmail.com
mailchimp-list: https://ericlaurits.substack.com/p/coming-soon?r=dkri2&utm_campaign=post&utm_medium=web&utm_source=copy
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  eric:
    name: Eric
    site: seekthejoy.com
    avatar: "/assets/images/avatar1.jpg"
    bio: Hi, I am Sal, the author of Mundana, the theme you're currently previewing.
      I hope you like it!
    email: eric.laurits@gmail.com
    twitter: https://twitter.com/ericlaurits
  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, fashionista, love to explore new ideas and write on my morning coffee!
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet
defaults:
- scope: ''
  values: ''
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
